### ISSUE TITLE
Quarto error with Julia 1.8.1: ImportError: DLL load failed while importing error: Das angegebene Modul wurde nicht gefunden.

### ISSUE THREAD

**Issue by Patrikios** [quarto-dev/quarto-vscode#82]
quarto preview test.qmd  

Starting julia-1.8 kernel...Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\XXX\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 17, in <module>
    from nbclient import NotebookClient
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\nbclient\__init__.py", line 3, in <module>
    from .client import NotebookClient, execute  # noqa: F401
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\nbclient\client.py", line 21, in <module>
    from jupyter_client import KernelManager
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\zmq\__init__.py", line 55, in <module>
    from zmq import backend
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\XXX\.julia\conda\3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: Das angegebene Modul wurde nicht gefunden.

**Comment by vtfanta** [comment]
I am also experiencing this issue.
